import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Gamma Developers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full bg-transparent fixed inset-x-0 top-0 z-100">
          <Navbar />
        </div>

        {children}
      </body>
    </html>
  );
}
